### ISSUE TITLE
aws lambda without optimizations

### ISSUE THREAD

**Issue by garethmdavies** [nervous-systems/cljs-lambda#60] opened 2017-02-12 09:05 UTC
Hi, I'm trying to create a lambda using this cljs-lambda and https://github.com/r0man/sqlingvo.node in order to communicate with an postgres RDS db. I'm hitting a few problems which I think are related to advanced optimizations. I've tried to set the optimzation to none but I can't get a working lambda. I'm getting errors like 'Unable to import module 'index'. Are there any examples of cljs-lambda packages without advanced optimizations so I can compare to my project and rule this out?

**Comment by taffowl** [comment] 2017-02-12 09:33
I've uploaded a sample project here that I've been trying to get deployed in aws: https://github.com/taffowl/dblambda

**Comment by zrzka** [comment] 2017-02-12 09:41
I do use :none w/o issues. IIRC I had to set :main and goog.debug to false in :closure-defines. Can share config, but tomorrow when I'll have access to my computer.

**Comment by garethmdavies** [comment] 2017-02-12 09:45
Ok so my project that i'm trying to get working is here: https://github.com/taffowl/api-db-lambda-v2. (obviously the db connection string is different for my db). With optimizations set to :advanced I can see the lambda executes but fail with the following:

`START RequestId: 5314a2f5-f15e-11e6-9ce0-6db4d4f67b64 Version: $LATEST
2017-02-12T20:03:32.390Z	5314a2f5-f15e-11e6-9ce0-6db4d4f67b64	true
2017-02-12T20:03:32.570Z	5314a2f5-f15e-11e6-9ce0-6db4d4f67b64	TypeError: Gp.a(...).ke is not a function
    at Function.Gw.c (/var/task/target/api-db-lambda-v2/sqlingvo/node.cljs:64:15)
    at Gw (/var/task/target/api-db-lambda-v2/sqlingvo/node.cljs:56:1)
    at /var/task/target/api-db-lambda-v2/api_db_lambda_v2/core.cljs:15:3
    at b (/var/task/target/api-db-lambda-v2/api_db_lambda_v2/core.cljs:15:3)
    at d (/var/task/target/api-db-lambda-v2/api_db_lambda_v2/core.cljs:15:3)
    at pw (/var/task/target/api-db-lambda-v2/cljs/core/async/impl/ioc_helpers.cljs:35:5)
    at /var/task/target/api-db-lambda-v2/cljs/core/async/impl/ioc_helpers.cljs:48:39
    at /var/task/target/api-db-lambda-v2/cljs/core/async/impl/channels.cljs:74:39
    at Immediate.aw [as _onImmediate] (/var/task/target/api-db-lambda-v2/cljs/core/async/impl/dispatch.cljs:19:10)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
END RequestId: 5314a2f5-f15e-11e6-9ce0-6db4d4f67b64
REPORT RequestId: 5314a2f5-f15e-11e6-9ce0-6db4d4f67b64	Duration: 892.11 ms	Billed Duration: 900 ms 	Memory Size: 128 MB	Max Memory Used: 62 MB	
RequestId: 5314a2f5-f15e-11e6-9ce0-6db4d4f67b64 Process exited before completing request.`

I'm trying to work out whats happening with the TypeError and it's possible that sqingvo.node lib doesn't play nicely with advanced optimizations. To rule this out I've set this optimizations to :none and set :closures-defines to `{"goog.DEBUG" false}}` as mentioned above however the lambda fails to even execute with: `module initialization error: Error`

`{"errorMessage": "callback called with Error argument, but there was a problem while retrieving one or more of its message, name, and stack"}`

My goal is simply to build a lambda with cljs-lambda to take advantage of the speedy cold start up time over a pure clojure lambda. The lambda will be invoked by api gateway and will query my RDS postgres instance over ssl. In pure clojure world I have a lambda working fine but really keen to use clojurescript for this.

**Comment by moea** [comment] 2017-02-12 11:30
'unable to load module index' will be caused by any top-level exception in code referenced in your handlers - it's an error thrown by the Node process AWS Lambda uses to `require` your code. Using advanced compilation with a third party JS library won't work unless you supply an externs file to the clojurescript compiler, as in vanilla cljs code. So it probably makes sense to focus on 'none' initially. 

Any example which uses advanced should work with none (eg the example/ dir in the repository), if the project file is updated.

**Comment by moea** [comment] 2017-02-12 22:53
@taffowl Advanced optimisations will break in the same way that it would if you ran the code locally - the Closure compiler doesn't know anything about the functions defined in the third-party node module (`pg`), and is aggressively renaming at the call sites.  If `sqlinvgo` had an externs file for the modules it's requiring, it'd let the compiler know not to mangle the exported symbols.  But `advanced` is not a massive advantage, so let's forget about it for now.

For debugging optimisations `none` locally:

```
$ lein cljs-lambda build
$ cp target/api-db-lambda-v2/index.js .
$ node index.js
```

In your case, it runs fine - so I deployed it.  The database initialisation at the module level is going to make it harder to figure out exactly what's going wrong, because Lambda doesn't provide meaningful stack traces if its `require('index')` blows up.  I did these things in sequence:

 - Change the module to construct the database inside the handler - same error
 - Remove sqlinvgo imports entirely, have handler just return a string - works
 - Add back sqlvingo.core import, without sqlinvgo.db - works
 - Remove sqlinvgo.core, change handler body to just `(nodejs/require "pg")`

The error I got was `/var/task/node_modules/libpq/build/Release/addon.node: invalid ELF header:` -because my local addon.node (`Mach-O 64-bit bundle x86_64`) is meaningless on the Amazon Linux instance it's being copied to.  Assuming that's similar to what's happening for you, I'd suggest starting an ec2 instance from the Lambda AMI - `amzn-ami-hvm-2016.03.3.x86_64-gp2` (or using `docker-lambda`) and going through the `node index.js` junk from above, to verify that the pg module works on that platform, if it's built there.  If so, then one approach would be confining deployments to a docker image or machine that's going to generate a binary-compatible `addon.node`.  Alternatively you could build the binaries once, and substitute them into the Lambda zip file - I can't tell you for sure whether cljs-lambda's `:resource-dirs` will correctly overwrite an existing zip entry for something under `nodule_modules`, so that approach may require some hacking.

Let me know if I can help further.

**Comment by garethmdavies** [comment] 2017-02-13 09:20
@moea thats a superb write up thanks. I was wondering if there was a way to debug locally so I'll give docker-lambda a go. If I can get this working I'll get a blog post written up as I feel it's a common use case for lambdas.

**Comment by moea** [comment] 2017-02-13 09:39
@taffowl That'd be great!  Let me know if you run into issues putting the dockerfile together. I've made build images based on `amazonlinux:2016.09` (which is close enough - there isn't an official repo/tag for the precise version used on Lambda) - which may be more convenient for _building_ than docker-lambda, which tries to emulate the runtime environment (and for all I know, yum doesn't work, or has been removed - now that I'm thinking about it).

**Comment by zrzka** [comment] 2017-02-13 10:19
Just in case you'll want to check what's inside this image:

* https://github.com/aws/amazon-linux-docker-images/tree/2016.09-with-sources
* And 2016.09 vs 2016.03 - https://github.com/aws/amazon-linux-docker-images/issues/3

**Comment by garethmdavies** [comment] 2017-02-22 21:58
So I went through a process of elimination including building the lambda in an AWS docker container but still hit the same TypeError problem I had from the beginning. My next step was to rule out the connection to RDS from my lambda so I wrote a pure node app using the pg library and was able to successfully connect over ssl. (This is because you don't need to install the public key in order to get a full certificate verification; this is all handled by AWS.)

I then decided to use the following boot project to build my lambda using the simple optimisation defaults https://github.com/OffCourse

The cljs lambda worked first time so I came to the conclusion that the advanced optimizations were still the cause of the problems for me. I ended up forking cljs-lambda and adding crude support for simple optimizations using a new mustache template and a change to the zip packaging. The good news is I can build cljs  lambda now without any issues when running them. I did find it wasn't necessary for me to include libpq in the lambda zip which also helped me get around the invalid ELF header issue.

**Comment by moea** [comment] 2017-02-22 23:10
@taffowl I'm glad you're making progress - FWIW lein-cljs-lambda 0.6.5-SNAPSHOT has support for simple optimisations. If you get time, it'd be great to hear whether it's sufficient for your use case, and/or [differs](https://github.com/nervous-systems/cljs-lambda/commit/bd576790f9b41dc6849dee39477d42db5e0c7de1) from what you implemented, because I'm not currently using it with any rigour.

**Comment by moea** [comment] 2017-03-30 21:10
Closing, as 0.6.5 seems to be working with `:simple` w/out issues.

**Closed as completed by moea** 2017-03-30 21:10 UTC
